export interface GolferClub {
    id?: string; // Optional: Auto-generated by the database
    golfer_id: string;
    golfclub_id: string;
    golfbag_id: string;
    rounds: BigInt;
    shots: BigInt;
  }
  