export interface GolfClub {
  id?: string; // Optional: Auto-generated by the database
  golf_bag_id?: string;
  name: string;
  first: string; // First Name
  last: string; // Last Name
  loft: string; // Loft Value (e.g., "10.5°")
  lie_angle: string; // Lie Angle (e.g., "58°")
  club_offset: string; // club_offset (e.g., "0.1 inch")
  length: string; // Length (e.g., "35.5 inch")
  bounce: string; // Bounce (e.g., "12°")
}
